name: Generate artifacts for 0.1/base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-erc-for-0-1-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Ensure erc success
      run: |
        ./ninja.sh build/0.1/base/erc_success

  run-drc-for-0-1-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Ensure erc success
      run: |
        ./ninja.sh build/0.1/base/drc_success
  
  generate-artifacts-for-0-1-base:
    needs:
      [run-erc-for-0-1-base, run-drc-for-0-1-base]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Generate artifacts
      run: |
        ./ninja.sh 0.1/base
    - name: Upload generated files to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/0.1/base/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: "Automatically generated files for ferris 0.1 base variant"
