name: Check Design Rules and Electrical Rules for all variants

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-drc:
    strategy:
      matrix:
          variant: [0.1/base, 0.1/compact, 0.1/high, 0.1/low, 0.2/bling, 0.2/compact, 0.2/high, 0.2/mini]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Design rules check
      run: |
        ./automation/ninja.sh build/${{ matrix.variant }}/ferris.kicad_pcb.drc_success

  run-erc:
    strategy:
      matrix:
          variant: [0.1/base, 0.1/compact, 0.1/high, 0.1/low, 0.2/bling, 0.2/compact, 0.2/high, 0.2/mini]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Electrical rules check
      run: |
        ./automation/ninja.sh build/${{ matrix.variant }}/ferris.sch.erc_success
